# Generated by Django 2.2.3 on 2020-05-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='shape',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Форма'),
        ),
    ]
